### PR TITLE
added missing users/show.erb to file structure

### PR DESCRIPTION
**Pull request by itzsaga**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by Lukeghenco** [comment]
@itzsaga thank you for this PR, but I don't see anywhere where the tests require a users/show route or why we would need it for this application? Would you be able to add some clarification on why this needs to be added to the README.md?

**Comment by itzsaga** [comment]
I honestly do not know. What does "This pull request has been automatically created by learn.co." mean @lukeghenco?

**Comment by Lukeghenco** [comment]
@itzsaga thanks! I am not sure why that is popping up? was that is an email? I did find the test for this right after I sent that message.

**Comment by Lukeghenco** [comment]
```

**Comment by Lukeghenco** [comment]
Going to go ahead and merge this in thanks.

**Pull request merged**
